#!/usr/bin/env python3
"""Generate RTL defaults, linker map and C constants from config/memory.json."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if generated files are stale')
    args = parser.parse_args()
    cfg = json.loads((ROOT / 'config/memory.json').read_text())
    prog_bits = cfg['program_word_address_bits']
    data_bits = cfg['data_word_address_bits']
    origin = cfg['data_origin']
    if not (1 <= prog_bits <= 20 and 1 <= data_bits <= 20):
        parser.error('configured word address widths must be in [1, 20]')
    prog_bytes, data_bytes = 4 << prog_bits, 4 << data_bits
    if origin < 0 or origin % 4 or origin >= data_bytes:
        parser.error('data_origin must be aligned and inside data RAM')
    files = {
        'rtl/MemoryConfigPkg.sv': f'''// Generated by sw/scripts/generate_memory_config.py; edit config/memory.json.
`timescale 1ns/1ps
package MemoryConfigPkg;
    localparam int PROG_MEM_ADDR_BITS = {prog_bits};
    localparam int DATA_MEM_ADDR_BITS = {data_bits};
    localparam int DATA_ORIGIN = {origin};
endpackage
''',
        'sw/memory_config.h': f'''/* Generated from config/memory.json. */
#ifndef MEMORY_CONFIG_H
#define MEMORY_CONFIG_H
#define PROGRAM_MEMORY_BYTES {prog_bytes}u
#define DATA_MEMORY_BYTES {data_bytes}u
#define DATA_ORIGIN {origin}u
#endif
''',
        'sw/linker.ld': f'''/* Generated from config/memory.json. Harvard instruction/data memories. */
MEMORY
{{
    rom (rx) : ORIGIN = 0, LENGTH = {prog_bytes}
    ram (rw) : ORIGIN = {origin}, LENGTH = {data_bytes - origin}
}}
ENTRY(_start)
SECTIONS
{{
    .text : {{ KEEP(*(.text.init)) *(.text*) }} > rom
    .data ORIGIN(ram) : {{ __data_start = .; *(.rodata*) *(.srodata*) *(.data*) *(.sdata*) __data_end = .; }} > ram
    .bss (NOLOAD) : {{ . = ALIGN(4); __bss_start = .; *(.bss*) *(.sbss*) *(COMMON) . = ALIGN(4); __bss_end = .; }} > ram
    __stack_top = ORIGIN(ram) + LENGTH(ram);
    ASSERT(__bss_end <= __stack_top - 256, "RAM must leave at least 256 bytes for stack")
    /DISCARD/ : {{ *(.comment) *(.note*) *(.riscv.attributes) *(.eh_frame*) }}
}}
''',
    }
    stale = []
    for name, contents in files.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != contents:
                stale.append(name)
        else:
            path.write_text(contents)
    if stale:
        parser.exit(1, 'Stale memory configuration: ' + ', '.join(stale) + '\nRun python3 sw/scripts/generate_memory_config.py\n')


if __name__ == '__main__':
    main()
