// Generated by sw/scripts/generate_memory_config.py; edit config/memory.json.
`timescale 1ns/1ps
package MemoryConfigPkg;
    localparam int PROG_MEM_ADDR_BITS = 9;
    localparam int DATA_MEM_ADDR_BITS = 9;
    localparam int DATA_ORIGIN = 256;
endpackage
